### ISSUE TITLE
Excessive memory utilisation

### ISSUE THREAD

**Issue by keirlawson** [SystemFw/upperbound#13]
When using UpperBound for a large number of tasks, I am noticing what appears to be excessive memory utilisation.  With the below snippet:

```scala
object Main extends StreamApp[IO] {

  def randIO: IO[Unit] = {
    val randString = Random.alphanumeric.take(32).mkString
    IO(println(randString))
  }

  val awaitList = new util.LinkedList[IO[Unit]]

  def enqueueTasks(fixedRate: Stream[IO, Unit], task: => IO[Unit]): Stream[IO, Unit] = {
    fixedRate.evalMap { _ =>
      val startedTask = task.start.as(())
      awaitList.push(startedTask)
      startedTask
    }
  }

  override def stream(args: List[String], requestShutdown: IO[Unit]): fs2.Stream[IO, StreamApp.ExitCode] = {
    val prog = for {
      sched <- Scheduler[IO](8)
      fr = sched.fixedRate[IO](1.millisecond)
      lim <- Limiter.stream[IO](10 every 1.minute)
      sm <- enqueueTasks(fr, { lim.worker.await(randIO) })
    } yield sm

    prog.drain.as(ExitCode.Success)
  }

}
```

taking a heap dump roughly 10 minutes after kicking it off I see memory usage of 850mb and 39.3 million objects, most which appear to be instances of `cats.effect.IO`:

![upperboundheap](https://user-images.githubusercontent.com/49213/47302628-e20f9a80-d619-11e8-9a1b-feee11acd9d6.png)

This dwarfs the notional payload size (the `char[]`s)

Compare this to a similar example but without UpperBound and the memory usage is an order of magnitude smaller (around 90mb) and far less dominated by `cats.effect.IO`:

```scala
object Main extends StreamApp[IO] {

  def randIO: IO[Unit] = {
    val randString = Random.alphanumeric.take(32).mkString
    IO(println(randString))
  }

  def enqueueTasks(fixedRate: Stream[IO, Unit], task: => IO[Unit]): Stream[IO, Unit] = {
    fixedRate.evalMap { _ =>
      task
    }
  }

  override def stream(args: List[String], requestShutdown: IO[Unit]): fs2.Stream[IO, StreamApp.ExitCode] = {
    val prog = for {
      sched <- Scheduler[IO](8)
      fr = sched.fixedRate[IO](1.millisecond)
      qu <- Stream.eval(Queue.unbounded[IO, IO[Unit]])
      sm <- enqueueTasks(fr, { qu.enqueue1(randIO) })
    } yield sm

    prog.drain.as(ExitCode.Success)
  }

}
```

**Comment by keirlawson** [comment]
Dependecy list:

```
[info] co.fs2:fs2-core_2.12:0.10.6
[info] default:ub-test_2.12:0.0.1-SNAPSHOT
[info] org.scala-lang:scala-reflect:2.12.7
[info] org.systemfw:upperbound_2.12:0.1.1
[info] org.typelevel:cats-core_2.12:1.4.0
[info] org.typelevel:cats-effect_2.12:0.10.1
[info] org.typelevel:cats-kernel_2.12:1.4.0
[info] org.typelevel:cats-macros_2.12:1.4.0
[info] org.typelevel:dogs-core_2.12:0.6.10
[info] org.typelevel:machinist_2.12:0.6.5
```

**Comment by SystemFw** [comment]
First thing that strikes me is that the two snippets aren't the same because you're not awaiting in the second one

**Comment by SystemFw** [comment]
In fact, you are not dequeueing at all

**Comment by keirlawson** [comment]
They are not exactly equivalent true, though I would have assumed if anything not dequeing would have lead to greater memory utilisation.

**Comment by SystemFw** [comment]
> though I would have assumed if anything not dequeing would have lead to greater memory utilisation.

I'm not sure, there's less `IO` happening. As a separate point, `await` needs to allocate a `Promise` as well. Not saying that this is the issue, but worth keeping it in mind if you're doing comparisons

**Comment by keirlawson** [comment]
Swapping out `await` for `submit` in my original snipped reduces memory usage roughly in half, 360mb and 15.2 million objects:
 
![submit](https://user-images.githubusercontent.com/49213/47369533-d4bae480-d6db-11e8-8fea-d94432dfb4b9.png)

**Comment by SystemFw** [comment]
Ok, I don't think it's the root cause but it's closer to understanding what's going on

**Comment by SystemFw** [comment]
can you try with master as well when you have time?

**Comment by keirlawson** [comment]
FWIW adding a dequeue to the UpperBound-less snippet above still has memory usage around the 100 mb mark.

**Comment by SystemFw** [comment]
yeah. Next steps would be to run on master, and then to check only upperbound-less snippet, but with the upperbound internal queues vs the fs2 queue and see what happens

**Comment by SystemFw** [comment]
Any updates on this? were you able to ascertain whether this was heavy but constant overhead or an actual leak?

In any case, I'm probably changing the internal queue implementation to be more resilient wrt interruption (which wasn't possible when the library was first written)

**Comment by keirlawson** [comment]
From debugging a similar issue in abother application I am fairly convinced that this is an inherent cost in doing everything in `IO`, the memory usage scales linearly with the queue size.
