### ISSUE TITLE
Create microsite

### ISSUE THREAD

**Issue by SystemFw** [SystemFw/upperbound#17]
It would be nice to convert the readme to a microsite, and it shouldn't be too hard either, but I'm quite short on time. If someone wants to step in, I'll gladly take a PR.

**Comment by SystemFw** [comment]
Note: use `mdoc` and `docusaurus` like in https://github.com/ovotech/dynosaur

**Comment by mgibowski** [comment]
How about `sbt-microsites` instead of `docusaurus`? Version 1.0 [released this week](https://www.47deg.com/blog/sbt-microsites-v-1-0-0-release/) looks quite good and supports `mdoc` by default. The advantage would be that scala-steward would be taking care of its updates.
