### ISSUE TITLE
Support rate limiting streams

### ISSUE THREAD

**Issue by keirlawson** [SystemFw/upperbound#3]
It would be great to be able to input a stream and and receive back a rate-limited stream which could then be mapped/flatMapped etc

**Comment by SystemFw** [comment]
I reached the conclusion that this is basically a different abstraction.
First of all, most cases where you have something like a `Stream[F, Request]` and you want to make rate limited api calls can be handled with `evalMap` or `mapAsync`.
The remaining cases are things where you want to throttle a _single_ stream, in the sense of having it emit elements slower, which you can already do with `zipLeft(fixedRate)` or something like that.

Therefore, I'm closing this for now, but I would consider a PR if you can find an abstraction that fits the throttling case and can't be done with simple `fs2` combinators, or a new convincing use case for this that can't be done with the current api.
