### ISSUE TITLE
Add BackPressure method for specific duration

### ISSUE THREAD

**Issue by Daenyth** [SystemFw/upperbound#8]
Some applications might know how long they need to wait between requests, adding a `BackPressure.fromElement(f: A => Option[FiniteDuration])` handler would be helpful.

A use case for this would be calling a rate-limiting API which informs the caller of quota usage on every response

**Comment by SystemFw** [comment]
That's indeed a good use case, but I don't think it can be supported in the current api.
I'll need to have a think about redesigning that aspect of the interface.
Roughly related to #2

**Comment by SystemFw** [comment]
The api in the newest version allows this quite easily

```scala
def yourTask: F[FiniteDuration]

def combinator[F[_]: Limiter] = Limiter[F].submit {
    yourTask.flatTap(Limiter[F].interval.set)
}
```
