### ISSUE TITLE
Cats Effect 3 support 

### ISSUE THREAD

**Issue by DarkWingMcQuack** [SystemFw/upperbound#86]
are there any plans on supporting cats effect 3 and fs2-3?

**Comment by SystemFw** [comment]
Now that I know that there is at least one person that cares, yes!
I'm trying to decide on the best strategy: I have a redesign in mind, simplifying the api a bit, but perhaps I would first release a CE3 update with no changes.

**Comment by DarkWingMcQuack** [comment]
Sounds awesome, thank you

**Comment by SystemFw** [comment]
Hey, this is taking some time cause I need to get through some chores (setting CI releases etc), but I haven't forgotten

**Comment by SystemFw** [comment]
Very informal poll: does anyone use the Backpressure stuff? I'm pretty unsatisfied with it and I'm thinking of removing it, since you have the raw power to modify the rate via `interval` anyway

**Comment by DarkWingMcQuack** [comment]
Haha, the thumbs down means "i do not use the Backpressure stuff" :smile:

**Comment by nafg** [comment]
Hi, any update?

If Backpressure is a public API and the question is do people use it directly, personally I haven't

**Comment by jglynn43** [comment]
Adding my two cents: very much looking forward to this and I don't use Backpressure

**Comment by SystemFw** [comment]
Btw I'm working on it on the `ce3` branch

**Comment by SystemFw** [comment]
I'm in the process of writing docs, and potentially some more tests for new functionality, but core library is pretty much ready. However, a stable version cannot be published until cats-effect 3.3 is out

> This is overall not much different than fs2.Stream.metered

`metered` doesn't allow you to submit jobs concurrently, nor to cancel jobs, nor to have jobs at different priority.

> we are interested in the ability to make it flexible via BackPressure

I won't be reintroducing the BackPressure abstraction, there are two many caveats to its usage.
At the moment, the next version doesn't allow any form of adjustable rate via SignallingRef either, but I'm planning to reintroduce that at some point. The main hurdle there is that upperbound now also allows control over the maximum number of  jobs running concurrently, and making _that_ adjustable in flight is much more challenging.

**Comment by SystemFw** [comment]
I've released v0.4.0-M1 on Sonatype, currently syncing with Maven Central. It has most of the api except adjustable controls. I'm working on those in the `adjustable` branch, mostly lacking concurrency tests at the moment

**Comment by SystemFw** [comment]
Ok, I've released v0.4.0-M2 on Sonatype, currently syncing. It adds dynamically adjustable controls over both rate and concurrency. I think the api is now complete, and I will release a final version in the next few days.

**Comment by SystemFw** [comment]
Well, it took me longer than expected but I did get to a final release. No api changes since M2, but fixed an inconsistency in the semantics of interruption. It should be syncing now.
